<a href="https://colab.research.google.com/github/Karthikbv29/Batch108/blob/main/Telecom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
tel=pd.read_csv('telco_data.csv')

In [ ]:
tel.head(10)

International.Plan Voice.Mail.Plan  X..Vmail.Messages  Total.Day.Minutes  \
0                 no             yes                 25              265.1   
1                 no             yes                 26              161.6   
2                 no              no                  0              243.4   
3                yes              no                  0              299.4   
4                yes              no                  0              166.7   
5                yes              no                  0              223.4   
6                 no             yes                 24              218.2   
7                yes              no                  0              157.0   
8                 no              no                  0              184.5   
9                yes             yes                 37              258.6   

   Total.Day.Calls  Total.Day.Charge  Total.Eve.Minutes  Total.Eve.Calls  \
0              110             45.07              197.4               99   
1              123             27.47              195.5              103   
2              114             41.38              121.2              110   
3               71             50.90               61.9               88   
4              113             28.34              148.3              122   
5               98             37.98              220.6              101   
6               88             37.09              348.5              108   
7               79             26.69              103.1               94   
8               97             31.37              351.6               80   
9               84             43.96              222.0              111   

   Total.Eve.Charge  Total.Night.Minutes  Total.Night.Calls  \
0             16.78                244.7                 91   
1             16.62                254.4                103   
2             10.30                162.6                104   
3              5.26                196.9                 89   
4             12.61                186.9                121   
5             18.75                203.9                118   
6             29.62                212.6                118   
7              8.76                211.8                 96   
8             29.89                215.8                 90   
9             18.87                326.4                 97   

   Total.Night.Charge  Total.Intl.Minutes  Total.Intl.Calls  \
0               11.01                10.0                 3   
1               11.45                13.7                 3   
2                7.32                12.2                 5   
3                8.86                 6.6                 7   
4                8.41                10.1                 3   
5                9.18                 6.3                 6   
6                9.57                 7.5                 7   
7                9.53                 7.1                 6   
8                9.71                 8.7                 4   
9               14.69                11.2                 5   

   Total.Intl.Charge  X..customer.Service.Calls   Churn trainrows  
0               2.70                          1  False.        No  
1               3.70                          1  False.       Yes  
2               3.29                          0  False.       Yes  
3               1.78                          2  False.       Yes  
4               2.73                          3  False.       Yes  
5               1.70                          0  False.       Yes  
6               2.03                          3  False.        No  
7               1.92                          0  False.       Yes  
8               2.35                          1  False.       Yes  
9               3.02                          0  False.       Yes

In [ ]:
tel.shape

(5000, 18)

In [ ]:
tel.isna().sum()

International.Plan           0
Voice.Mail.Plan              0
X..Vmail.Messages            0
Total.Day.Minutes            0
Total.Day.Calls              0
Total.Day.Charge             0
Total.Eve.Minutes            0
Total.Eve.Calls              0
Total.Eve.Charge             0
Total.Night.Minutes          0
Total.Night.Calls            0
Total.Night.Charge           0
Total.Intl.Minutes           0
Total.Intl.Calls             0
Total.Intl.Charge            0
X..customer.Service.Calls    0
Churn                        0
trainrows                    0
dtype: int64

In [ ]:
tel.dtypes

International.Plan            object
Voice.Mail.Plan               object
X..Vmail.Messages              int64
Total.Day.Minutes            float64
Total.Day.Calls                int64
Total.Day.Charge             float64
Total.Eve.Minutes            float64
Total.Eve.Calls                int64
Total.Eve.Charge             float64
Total.Night.Minutes          float64
Total.Night.Calls              int64
Total.Night.Charge           float64
Total.Intl.Minutes           float64
Total.Intl.Calls               int64
Total.Intl.Charge            float64
X..customer.Service.Calls      int64
Churn                         object
trainrows                     object
dtype: object

In [ ]:
tel.columns

Index(['International.Plan', 'Voice.Mail.Plan', 'X..Vmail.Messages',
       'Total.Day.Minutes', 'Total.Day.Calls', 'Total.Day.Charge',
       'Total.Eve.Minutes', 'Total.Eve.Calls', 'Total.Eve.Charge',
       'Total.Night.Minutes', 'Total.Night.Calls', 'Total.Night.Charge',
       'Total.Intl.Minutes', 'Total.Intl.Calls', 'Total.Intl.Charge',
       'X..customer.Service.Calls', 'Churn', 'trainrows'],
      dtype='object')

In [ ]:
num=['X..Vmail.Messages',
       'Total.Day.Minutes', 'Total.Day.Calls', 'Total.Day.Charge',
       'Total.Eve.Minutes', 'Total.Eve.Calls', 'Total.Eve.Charge',
       'Total.Night.Minutes', 'Total.Night.Calls', 'Total.Night.Charge',
       'Total.Intl.Minutes', 'Total.Intl.Calls', 'Total.Intl.Charge',
       'X..customer.Service.Calls']
cat=['International.Plan', 'Voice.Mail.Plan', 'trainrows']       

In [ ]:
num

['X..Vmail.Messages',
 'Total.Day.Minutes',
 'Total.Day.Calls',
 'Total.Day.Charge',
 'Total.Eve.Minutes',
 'Total.Eve.Calls',
 'Total.Eve.Charge',
 'Total.Night.Minutes',
 'Total.Night.Calls',
 'Total.Night.Charge',
 'Total.Intl.Minutes',
 'Total.Intl.Calls',
 'Total.Intl.Charge',
 'X..customer.Service.Calls']

In [ ]:
for col in cat:
  tel[col]=tel[col].astype('category')

In [ ]:
tel.dtypes

International.Plan           category
Voice.Mail.Plan              category
X..Vmail.Messages               int64
Total.Day.Minutes             float64
Total.Day.Calls                 int64
Total.Day.Charge              float64
Total.Eve.Minutes             float64
Total.Eve.Calls                 int64
Total.Eve.Charge              float64
Total.Night.Minutes           float64
Total.Night.Calls               int64
Total.Night.Charge            float64
Total.Intl.Minutes            float64
Total.Intl.Calls                int64
Total.Intl.Charge             float64
X..customer.Service.Calls       int64
Churn                        category
trainrows                    category
dtype: object

In [ ]:
tel.nunique()

International.Plan              2
Voice.Mail.Plan                 2
X..Vmail.Messages              48
Total.Day.Minutes            1961
Total.Day.Calls               123
Total.Day.Charge             1961
Total.Eve.Minutes            1879
Total.Eve.Calls               126
Total.Eve.Charge             1659
Total.Night.Minutes          1853
Total.Night.Calls             131
Total.Night.Charge           1028
Total.Intl.Minutes            170
Total.Intl.Calls               21
Total.Intl.Charge             170
X..customer.Service.Calls      10
Churn                           2
trainrows                       2
dtype: int64

In [ ]:
tel.describe()

X..Vmail.Messages  Total.Day.Minutes  Total.Day.Calls  \
count        5000.000000        5000.000000      5000.000000   
mean            7.755200         180.288900       100.029400   
std            13.546393          53.894699        19.831197   
min             0.000000           0.000000         0.000000   
25%             0.000000         143.700000        87.000000   
50%             0.000000         180.100000       100.000000   
75%            17.000000         216.200000       113.000000   
max            52.000000         351.500000       165.000000   

       Total.Day.Charge  Total.Eve.Minutes  Total.Eve.Calls  Total.Eve.Charge  \
count       5000.000000        5000.000000      5000.000000       5000.000000   
mean          30.649668         200.636560       100.191000         17.054322   
std            9.162069          50.551309        19.826496          4.296843   
min            0.000000           0.000000         0.000000          0.000000   
25%           24.430000         166.375000        87.000000         14.140000   
50%           30.620000         201.000000       100.000000         17.090000   
75%           36.750000         234.100000       114.000000         19.900000   
max           59.760000         363.700000       170.000000         30.910000   

       Total.Night.Minutes  Total.Night.Calls  Total.Night.Charge  \
count          5000.000000        5000.000000         5000.000000   
mean            200.391620          99.919200            9.017732   
std              50.527789          19.958686            2.273763   
min               0.000000           0.000000            0.000000   
25%             166.900000          87.000000            7.510000   
50%             200.400000         100.000000            9.020000   
75%             234.700000         113.000000           10.560000   
max             395.000000         175.000000           17.770000   

       Total.Intl.Minutes  Total.Intl.Calls  Total.Intl.Charge  \
count         5000.000000       5000.000000        5000.000000   
mean            10.261780          4.435200           2.771196   
std              2.761396          2.456788           0.745514   
min              0.000000          0.000000           0.000000   
25%              8.500000          3.000000           2.300000   
50%             10.300000          4.000000           2.780000   
75%             12.000000          6.000000           3.240000   
max             20.000000         20.000000           5.400000   

       X..customer.Service.Calls  
count                5000.000000  
mean                    1.570400  
std                     1.306363  
min                     0.000000  
25%                     1.000000  
50%                     1.000000  
75%                     2.000000  
max                     9.000000

In [ ]:
x=tel.drop('Churn',axis=1)
y=tel['Churn']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=29)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(3500, 17)
(1500, 17)
(3500,)
(1500,)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train[num])
x_train_std=sc.transform(x_train[num])
x_test_std=sc.transform(x_test[num])

In [ ]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
ohe=OneHotEncoder()
ohe.fit(x_train[cat])
x_train_ohe=ohe.transform(x_train[cat]).toarray()
x_test_ohe=ohe.transform(x_test[cat]).toarray()

le=LabelEncoder()
le.fit(y_train)
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [ ]:
x_train=np.concatenate([x_train_ohe,x_train_std],axis=1)
x_test=np.concatenate([x_test_ohe,x_test_std],axis=1)

In [ ]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(x_train,y_train)
trainpreds_log=log.predict(x_train)
testpreds_log=log.predict(x_test)

In [ ]:
def evaluate_model(act, pred):
    from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score
    print("Confusion Matrix \n", confusion_matrix(act, pred))
    print("Accuracy : ", accuracy_score(act, pred))
    print("Recall   : ", recall_score(act, pred))
    print("Precision: ", precision_score(act, pred))  

In [ ]:
print('----train----')
evaluate_model(y_train,trainpreds_log)
print('----test----')
evaluate_model(y_test,testpreds_log)

----train----
Confusion Matrix 
 [[2917   74]
 [ 417   92]]
Accuracy :  0.8597142857142858
Recall   :  0.1807465618860511
Precision:  0.5542168674698795
----test----
Confusion Matrix 
 [[1268   34]
 [ 144   54]]
Accuracy :  0.8813333333333333
Recall   :  0.2727272727272727
Precision:  0.6136363636363636


In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
trainpreds_dt=dt.predict(x_train)
testpreds_dt=dt.predict(x_test)

In [ ]:
print('----train----')
evaluate_model(y_train,trainpreds_dt)
print('----test----')
evaluate_model(y_test,testpreds_dt)

----train----
Confusion Matrix 
 [[2991    0]
 [   0  509]]
Accuracy :  1.0
Recall   :  1.0
Precision:  1.0
----test----
Confusion Matrix 
 [[1222   80]
 [  51  147]]
Accuracy :  0.9126666666666666
Recall   :  0.7424242424242424
Precision:  0.6475770925110133


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
trainpreds_rf=rf.predict(x_train)
testpreds_rf=rf.predict(x_test)

In [ ]:
print('----train----')
evaluate_model(y_train,trainpreds_rf)
print('----test----')
evaluate_model(y_test,testpreds_rf)

----train----
Confusion Matrix 
 [[2991    0]
 [   0  509]]
Accuracy :  1.0
Recall   :  1.0
Precision:  1.0
----test----
Confusion Matrix 
 [[1293    9]
 [  54  144]]
Accuracy :  0.958
Recall   :  0.7272727272727273
Precision:  0.9411764705882353


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
trainpreds_knn=knn.predict(x_train)
testpreds_knn=knn.predict(x_test)

In [ ]:
print('----train----')
evaluate_model(y_train,trainpreds_knn)
print('----test----')
evaluate_model(y_test,testpreds_knn)

----train----
Confusion Matrix 
 [[2980   11]
 [ 296  213]]
Accuracy :  0.9122857142857143
Recall   :  0.41846758349705304
Precision:  0.9508928571428571
----test----
Confusion Matrix 
 [[1294    8]
 [ 136   62]]
Accuracy :  0.904
Recall   :  0.31313131313131315
Precision:  0.8857142857142857


In [ ]:
cols=['Model','Train_Accuracy','Train_Precision','Train_Recall','Test_Accuracy','Test_Precision','Test_Recall']
performance=pd.DataFrame(columns=cols)

In [ ]:
def add_to_perf(df,model,train_act,train_pred,test_act,test_pred):
  from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score
  train_accuracy=accuracy_score(train_act,train_pred)
  test_accuracy=accuracy_score(test_act,test_pred)
  train_precision=precision_score(train_act,train_pred)
  test_precision=precision_score(test_act,test_pred)
  train_recall=recall_score(train_act,train_pred)
  test_recall=recall_score(test_act,test_pred)
  df=df.append(pd.Series([model,train_accuracy,train_precision, train_recall,test_accuracy,test_precision, test_recall],index=df.columns),ignore_index=True)
  return df

In [ ]:
performance=add_to_perf(performance,'Logistic Regression',y_train,trainpreds_log,y_test,testpreds_log)

In [ ]:
performance=add_to_perf(performance,'Decision Tree',y_train,trainpreds_dt,y_test,testpreds_dt)

In [ ]:
performance=add_to_perf(performance,'Random Forest',y_train,trainpreds_rf,y_test,testpreds_rf)

In [ ]:
performance=add_to_perf(performance,'K-Nearest Neighbors',y_train,trainpreds_knn,y_test,testpreds_knn)

In [ ]:
performance

Model  Train_Accuracy  Train_Precision  Train_Recall  \
0  Logistic Regression        0.859714         0.554217      0.180747   
1        Decision Tree        1.000000         1.000000      1.000000   
2        Random Forest        1.000000         1.000000      1.000000   
3  K-Nearest Neighbors        0.912286         0.950893      0.418468   

   Test_Accuracy  Test_Precision  Test_Recall  
0       0.881333        0.613636     0.272727  
1       0.912667        0.647577     0.742424  
2       0.958000        0.941176     0.727273  
3       0.904000        0.885714     0.313131